epoch: 500
seed: 1234
dynamic_loss_scaling: True
ignore_layers: []
save_checkpoint_per_steps: 1000
logging_per_steps: 1000

checkpoint_dir: 'outputs/checkpoints'
checkpoint: 'outputs/checkpoints/checkpoint_15800.pt'
device: 'cpu'
log_dir: 'outputs/logs'

reference_step: 100000
emotion2id:
  neutral: 0
  happy: 1
  sad: 2
  angry: 3

# reference encoder
E: 512
ref_enc_filters: [32, 32, 64, 64, 128, 128]
ref_enc_size: [3, 3]
ref_enc_strides: [2, 2]
ref_enc_pad: [1, 1]
ref_enc_gru_size: 128
# Style Token Layer
token_num: 20
num_heads: 8
n_mels: 80

id2emotion:
  0: neutral
  1: happy
  2: sad
  3: angry  

################################
# Data Parameters             #
################################
load_mel_from_disk: True
wav_dir: 'data/mels'
training_files: 'data/train.txt'
validation_files: 'data/test.txt'

################################
# Audio Parameters             #
################################
max_wav_value: 32768.0
sampling_rate: 22050
filter_length: 1024
hop_length: 256
win_length: 1024
n_mel_channels: 80
mel_fmin: 0.0
mel_fmax: 8000.0
n_frame_per_step: 1

################################
# Model Parameters             #
################################
n_symbols: 152
symbols_embedding_dim: 512

# Encoder parameters
encoder_kernel_size: 5
encoder_n_convolutions: 3
encoder_embedding_dim: 512

reference_dim: 128

# Decoder parameters
n_frames_per_step: 1  # currently only 1 is supported
decoder_rnn_dim: 1024
prenet_dim: 256
max_decoder_steps: 1000
gate_threshold: 0.5
p_attention_dropout: 0.1
p_decoder_dropout: 0.1

# Attention parameters
attention_rnn_dim: 1024
attention_dim: 128

# Location Layer parameters
attention_location_n_filters: 32
attention_location_kernel_size: 31

# Mel-post processing network parameters
postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 5

################################
# Optimization Hyperparameters #
################################
use_saved_learning_rate: False
learning_rate: 1e-3
weight_decay: 0.00001
grad_clip_thresh: 1.0
batch_size: 64
mask_padding: True 
